name: Generate GitHub Cards

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate SVGs
        run: |
          # ===== STATS =====
          curl "https://github-readme-stats.vercel.app/api?username=Lecloow&show_icons=true&theme=dark" -o stats-dark.svg
          curl "https://github-readme-stats.vercel.app/api?username=Lecloow&show_icons=true&theme=default" -o stats-light.svg

          # ===== AFFINITIES =====
          curl "https://github-readme-stats.vercel.app/api/pin/?username=Lecloow&repo=Affinities&theme=dark" -o affinities-dark.svg
          curl "https://github-readme-stats.vercel.app/api/pin/?username=Lecloow&repo=Affinities&theme=default" -o affinities-light.svg

          # ===== Papillon =====
          curl "https://github-readme-stats.vercel.app/api/pin/?username=PapillonApp&repo=Papillon&theme=dark" -o projet-dark.svg
          curl "https://github-readme-stats.vercel.app/api/pin/?username=PapillonApp&repo=Papillon&theme=default" -o projet-light.svg

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *.svg
          git commit -m "update cards" || exit 0
          git push
